import { IContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@4.1.0'
 */
export type HeroModel = IContentItem<{
  ctaUrl: Elements.TextElement;
  headline: Elements.TextElement;
  ctaLabel: Elements.TextElement;
  summary: Elements.TextElement;
}>;
